/**
 * Builds ui-hall/data/showcase.js (+ .json) — the data the site's home page
 * uses to present the MCP and the skill honestly: the real tool manifest,
 * real sample outputs produced by actually calling each tool, real stats.
 *
 *   node tools/build_showcase.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TOOLS, callTool, PATTERN_DEFS } from '../stormy-mcp/tools.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const CORPUS_PATH = path.join(ROOT, 'ui-hall', 'data', 'corpus.json');

const corpus = JSON.parse(fs.readFileSync(CORPUS_PATH, 'utf8'));
corpus.__path = CORPUS_PATH;

const clip = (obj, max = 900) => {
  const s = JSON.stringify(obj, null, 1);
  return s.length <= max ? s : s.slice(0, max).trimEnd() + '\n…';
};

const SAMPLES = [
  ['search_designs', { query: 'dark crypto wallet balance', limit: 3 }],
  ['design_brief', { screen: 'onboarding for a sleep tracking app', examples: 3 }],
  ['palette_for', { mood: 'warm and quiet', surface: 'dark', count: 2 }],
  ['list_groups', { limit: 3 }],
  ['get_asset', { id: 'IMG-0518' }],
  ['find_patterns', { about: 'dashboard', limit: 2 }],
  ['compare_pair', { topic: 'wallet balance', limit: 2 }],
  ['list_facets', { dimension: 'categories', limit: 6 }],
  ['corpus_stats', {}],
  ['asset_image', { id: 'IMG-0518', which: 'web' }],
];

const byId = new Map(corpus.assets.map((a) => [a.id, a]));

const tools = [];
for (const t of TOOLS) {
  const sample = SAMPLES.find(([n]) => n === t.name);
  let sampleOut = null;
  if (sample) {
    try {
      sampleOut = clip(await callTool(t.name, sample[1], corpus, HERE));
    } catch (err) {
      sampleOut = `error: ${err.message}`;
    }
  }
  tools.push({
    name: t.name,
    description: t.description,
    params: Object.entries(t.inputSchema.properties || {}).map(([k, v]) => ({
      name: k,
      type: v.type || 'any',
      description: v.description || '',
      required: (t.inputSchema.required || []).includes(k),
    })),
    sample_args: sample ? sample[1] : null,
    sample_output: sampleOut,
  });
}

const described = corpus.assets.filter((a) => a.description).length;
const clips = corpus.assets.filter((a) => a.clip).length;
const verifiedGroups = (corpus.groups || []).filter((g) => g.verified);

const showcase = {
  generated_at: new Date().toISOString(),
  stats: {
    assets: corpus.totals.assets,
    described,
    described_pct: Math.round((described / corpus.totals.assets) * 1000) / 10,
    clips,
    categories: (corpus.categories || []).length,
    groups: (corpus.groups || []).length,
    verified_groups: verifiedGroups.length,
    tags: (corpus.tags || []).length,
  },
  tools,
  groups: verifiedGroups.slice(0, 8).map((g) => ({
    id: g.id,
    title: g.title,
    members: g.members.map((m) => {
      const a = byId.get(m);
      return a ? { id: m, title: a.title, thumb: a.thumb } : null;
    }).filter(Boolean),
  })),
  patterns: PATTERN_DEFS.slice(0, 6).map((p) => ({ name: p.name, why: p.why })),
};

const outDir = path.join(ROOT, 'ui-hall', 'data');
fs.writeFileSync(path.join(outDir, 'showcase.json'), JSON.stringify(showcase, null, 1));
fs.writeFileSync(
  path.join(outDir, 'showcase.js'),
  '/* generated by tools/build_showcase.mjs — do not edit */\nwindow.SHOWCASE = ' +
    JSON.stringify(showcase) + ';\n'
);
console.log(
  `showcase: ${tools.length} tools, ${showcase.stats.assets} assets, ` +
  `${showcase.stats.verified_groups} verified groups -> ui-hall/data/showcase.js`
);
