#!/usr/bin/env python3
"""Fetch Poppins woff2 subsets from Google Fonts and write a self-hosted @font-face sheet.

    python tools/fetch_poppins.py

Poppins has no variable axis, so it ships as static weights. Google serves each
weight split by unicode-range (latin / latin-ext / devanagari); we mirror that
split locally, which means the Devanagari file is only downloaded by a browser
that actually meets a Devanagari glyph.

Re-runnable and idempotent: it re-downloads and rewrites in place.
"""
import os
import re
import urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Poppins:wght@400;500;600;700&display=swap")
# Google only serves woff2 to a modern UA string.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "ui-hall", "assets", "fonts", "poppins")
CSS_OUT = os.path.join(ROOT, "ui-hall", "assets", "css", "fonts.css")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = get(CSS_URL).decode("utf-8")

    # Each block is preceded by a /* subset */ comment naming the unicode range.
    blocks = re.findall(
        r"/\*\s*([a-z\-]+)\s*\*/\s*@font-face\s*\{(.*?)\}",
        css, re.S,
    )
    if not blocks:
        raise SystemExit("no @font-face blocks found - did Google change the response?")

    out = [
        "/* GENERATED by tools/fetch_poppins.py - do not edit by hand.",
        "   Poppins (SIL OFL 1.1), self-hosted. Google serves each weight split by",
        "   unicode-range; the split is mirrored here so a browser only downloads",
        "   the Devanagari file if the page actually contains a Devanagari glyph. */",
        "",
    ]
    total = 0
    for subset, body in blocks:
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        url = re.search(r"url\((https://[^)]+)\)", body).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()

        name = f"poppins-{weight}-{subset}.woff2"
        path = os.path.join(FONT_DIR, name)
        data = get(url)
        with open(path, "wb") as fh:
            fh.write(data)
        # A woff2 file starts with the ASCII magic "wOF2". Anything else means we
        # saved an error page.
        if data[:4] != b"wOF2":
            raise SystemExit(f"{name} is not a woff2 file (got {data[:16]!r})")
        total += len(data)

        out.append("@font-face {")
        out.append('  font-family: "Poppins";')
        out.append("  font-style: normal;")
        out.append(f"  font-weight: {weight};")
        out.append("  font-display: swap;")
        out.append(f'  src: url("../fonts/poppins/{name}") format("woff2");')
        out.append(f"  unicode-range: {urange};")
        out.append("}")
        out.append("")
        print(f"  {name:<28} {len(data) / 1024:6.1f} KB")

    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)
    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    print(f"\n{len(blocks)} faces, {total / 1024:.0f} KB total")
    print("wrote", CSS_OUT)


if __name__ == "__main__":
    main()
