"""Group screens that belong to the same app or the same design exploration.

The signal is the title, and deliberately nothing else.

A perceptual hash was tried first and removed: UI screenshots share a skeleton
(header, list, bottom bar) often enough that a 64-bit dHash collapsed 29
unrelated apps into a single group, and merged "Add Card" forms with map
screens. False grouping is worse than no grouping, because a wrong group
actively misleads. The leading words of a title are written by a person who was
looking at the screen, so they are the signal worth trusting.

Output is _work/meta/groups.json, which build_corpus folds into the corpus.
Re-running regenerates the file, so keep a copy if you hand-edit it.
"""
import json
import os
import re

ROOT = r"E:\Stormy"
CORPUS = os.path.join(ROOT, "ui-hall", "data", "corpus.json")
OUT = os.path.join(ROOT, "_work", "meta", "groups.json")

MIN_SIZE = 2
# Stopwords are dropped before the prefix is taken, so "The cart" and "cart"
# land in the same group while "cart" and "cartoon" stay apart.
STOP = {"the", "a", "an", "and", "with", "for", "in", "on", "of", "to", "vs"}
# How many significant leading words identify the screen. Two is the sweet spot:
# one merges unrelated apps that share a category word ("banking"), three splits
# a set that was obviously the same app.
PREFIX_WORDS = 2


def title_key(title):
    """The words that name the screen, not the variant or the crop."""
    t = (title or "").split(" — ")[0].split(" - ")[0]
    t = re.sub(r"[^a-z0-9 ]", "", t.lower()).strip()
    words = [w for w in t.split() if w not in STOP]
    return " ".join(words[:PREFIX_WORDS])


def slug(s):
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", s.lower())).strip("-")


def main():
    with open(CORPUS, encoding="utf-8") as fh:
        corpus = json.load(fh)
    assets = [a for a in corpus["assets"] if a["kind"] == "image"]

    by_title = {}
    for a in assets:
        k = title_key(a["title"])
        if k:
            by_title.setdefault(k, []).append(a)

    groups = []
    for key, members in sorted(by_title.items()):
        if len(members) < MIN_SIZE:
            continue
        members.sort(key=lambda a: a["id"])
        groups.append({
            "id": "GRP-" + slug(key),
            "title": members[0]["title"].split(" — ")[0].split(" - ")[0],
            "members": [m["id"] for m in members],
        })

    groups.sort(key=lambda g: (-len(g["members"]), g["id"]))

    payload = {
        "_note": "Generated by tools/group_screens.py from title prefixes. Screens "
                 "of the same app or the same exploration. Edit freely; re-running "
                 "overwrites, so keep a copy if you hand-tune.",
        "min_size": MIN_SIZE,
        "prefix_words": PREFIX_WORDS,
        "groups": groups,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=1, ensure_ascii=False)

    total = sum(len(g["members"]) for g in groups)
    print(f"groups: {len(groups)}  covering {total} of {len(assets)} images")
    for g in groups:
        print(f"  [{len(g['members'])}] {g['id']:<30} {' '.join(g['members'])}")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
