"""Extend the taxonomy with genuinely new concepts, and report near-duplicates.

    python tools/taxonomy_add.py            # dry run
    python tools/taxonomy_add.py --apply

Only concepts with no existing equivalent are added. Anything that a current
tag already covers is reported as a near-duplicate so the description can be
rewritten to use the canonical term instead of inventing a synonym.
"""
import json
import os
import sys

TAX = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "stormy-mcp", "taxonomy.json")

# new tag -> one-line definition. Add only when nothing existing covers it.
NEW_TAGS = {
    "chat-bubble": "Chat and message bubble styling.",
    "emoji": "Emoji used as UI content or as a reaction control.",
    "reaction": "Attached reactions (hearts, thumbs, taps) on content or messages.",
    "thread-reply": "A reply shown nested or quoted inside a conversation.",
    "link-preview": "A rich preview card generated from a shared URL.",
    "price": "Prices, cost figures and price-change indicators.",
    "rating-stars": "Star ratings and review scores.",
    "product-detail": "A single product's own page.",
    "product-grid": "A grid or list of multiple products.",
    "plant": "Botanical, foliage or plant-shop subject matter.",
    "moon": "Moon, night-sky or celestial imagery.",
    "divider": "Explicit separator rules or labelled dividers between blocks.",
    "option-list": "A list of tappable single-choice options.",
    "wellness-coach": "Habits, coaching, energy and daily check-in flows.",
    "sustainability": "Climate, environment and sustainability subject matter.",
    "chip-filter": "Compact pill-shaped filter chips.",
    "sorting": "Explicit sort control or a list stated to be sorted.",
    "line-art": "Illustration drawn as open outlines with no fills.",
    "testimonial": "A customer quote or review presented as social proof.",
    "composer": "The message-composition bar at the foot of a chat.",
    "dense-content": "Deliberately high information density in one view.",
    "multi-panel": "One image showing several app screens side by side.",
    "timestamp": "Relative or absolute time labels on items.",
    "assistant": "An AI assistant or agent as the product's subject.",
    "banner": "A wide promotional strip inserted into a list or feed.",
    "balance": "An account balance or headline monetary total.",
    "quick-actions": "A compact row of shortcut actions.",
    "heat-map": "A grid of intensity-shaded cells representing activity.",
    "legend": "A key explaining what colours or symbols mean.",
    "quiz": "A question-and-answer step inside a flow.",
    "recommendation": "Suggested content presented as a personal pick.",
    "numeral": "A very large display number used as the focal point.",
    "exploration": "Several layout variants shown together for comparison.",
    "address": "A postal or delivery address block.",
    "location": "A place, pin or map position.",
    "tracking": "Following an order, delivery or journey over time.",
    "artwork": "Cover or sleeve artwork as a focal image.",
    "chapter": "Chapter or segment list inside a long media item.",
    "sky": "Sky, cloud or weather imagery.",
    "atmospheric": "Mood-led imagery with no interface on it.",
    "automotive": "Vehicle, driving or in-car subject matter.",
    "course": "A structured learning programme or its unit.",
    "lesson": "A single teaching unit inside a course.",
    "electric-vehicle": "Battery, charging or EV-specific subject matter.",
    "transaction": "A money movement listed with merchant and amount.",
    "ledger": "A running list of dated monetary entries.",
    "flowers": "Floral or meadow subject matter.",
    "destination": "A travel place presented as the subject of the screen.",
    "authentication": "Sign-in, passkey or identity-verification steps.",
    "qr-code": "A QR code used as a scanner or pairing target.",
    "books": "Books, reading or a personal library.",
    "metric-tile": "A small boxed figure with a label, in a row of such boxes.",
    "running-route": "A recorded run or ride with a traced path.",
    "astrology": "Star signs, horoscopes and birth-chart subject matter.",
    "constellation": "Star patterns, celestial charts and night-sky linework.",
    "cosmic": "Space, planets and deep-sky imagery.",
    "zodiac": "A specific star sign and its reading.",
    "horoscope": "A dated personal reading for a sign.",
    "guidance": "Advice or a suggested course of action presented to the user.",
    "glyph": "A small abstract symbol used as an icon or chart marker.",
    "radial": "A chart or layout arranged around a centre point.",
    "nebula": "Soft cloud-like colour washes used as a background.",
    "level": "A numeric progression rank for the user.",
    "streak": "A count of consecutive days of activity.",
    "semantic-colour": "Hue used to carry state meaning rather than decoration.",
    "states": "A set of status values shown together as a component.",
    "brand-mark": "A logo, monogram or wordmark.",
    "single-colour": "One saturated colour used across a whole asset.",
    "budget": "Spending plans, savings targets and money allocation.",
    "report": "A summarised account of measured data.",
    "cover": "Cover or sleeve artwork as a focal image.",
    "segmented-control": "A row of mutually exclusive view options.",
    "audiobook": "Spoken-word book playback.",
    "classical": "Orchestral or historical classical-music repertoire.",
    "comment": "A user comment attached to a piece of content.",
    "concert": "Live-performance or stage imagery.",
    "contacts": "An address book of people.",
    "featured": "An editorially promoted item given hero treatment.",
    "full-bleed": "An image running edge to edge with no margin.",
    "gym": "Strength or gym-based training rather than running or cycling.",
    "session": "One bounded period of activity, with a start and an end.",
    "library": "A user's own saved collection.",
    "lyrics": "Song lyrics displayed alongside playback.",
    "membership": "A paid or tiered membership programme.",
    "points": "A loyalty or reward point balance.",
    "people": "Human subjects or a roster of named individuals.",
    "route": "A traced path between two points.",
    "scrubber": "A draggable playback or progress control.",
    "shelf": "A horizontally scrolling row of cards.",
    "specimen": "A component shown in isolation for reference.",
    "tiles": "A grid of small square shortcuts.",
    "track-list": "A list of songs with artist and duration.",
    "transfer": "Moving money between accounts or people.",
    "emphasis": "One item deliberately made visually dominant.",
    "upgrade": "An upsell toward a paid tier.",
    "timer": "A countdown or stopwatch as the primary control.",
    "payout": "Money paid out to a seller or creator.",
    "earning": "Income accrued by a seller or creator.",
    "revenue": "Top-line money earned, usually as a figure in a dashboard.",
    "creator": "Creator-economy tooling and reporting.",
    "trading": "Buying and selling of financial instruments.",
    "crypto": "Cryptocurrency holdings, tokens or wallets.",
    "restaurant": "Dining, ordering-at-table or table-booking subject matter.",
    "invite": "Inviting other people into a group or session.",
    "merchant": "A named business the user transacts with.",
    "expiry": "An expiry date or time limit on an offer.",
    "halftone": "A dot or line screen pattern used as texture.",
    "gauge": "A dial-style measurement rather than a bar.",
    "series": "Multiple data series plotted together.",
    "columns": "Charted columns, including mock-3D columns.",
    "icon-button": "An icon-only control with no visible label.",
    "toolbar": "A dense row or grid of editing controls.",
    "layer": "A z-order layer control inside an editor.",
    "history": "A chronological record of past actions.",
    "modes": "Named presets the user switches between.",
    "snapshot": "A single captured moment of a longer process.",
    "allocation": "Splitting a pot of money across categories or targets.",
    "campaign": "A time-boxed promotional or marketing push.",
    "cart": "A basket of items gathered before checkout.",
    "composition": "The arrangement of elements in a poster or key visual.",
    "shell": "The persistent outer frame of an app around its content.",
    "staging": "An area where work is prepared or held before going live.",
    "sticky": "An element pinned so it stays visible while the content scrolls.",
    "summary": "A condensed restatement of a longer set of details.",
    "winter": "Cold-season or snow subject matter.",
    # --- Hue vocabulary -----------------------------------------------------
    # The taxonomy previously had no colour terms at all, which is odd for a
    # design corpus: "show me every screen built on a lime accent" is one of the
    # most natural queries a designer would make. Name the hue only when it
    # carries the design (a single saturated accent or a monochrome ground), not
    # for incidental colour inside a photograph.
    "yellow": "Yellow as a screen's accent or dominant surface colour.",
    "lime": "Bright yellow-green as a screen's accent colour.",
    "mint": "Pale blue-green as a screen's accent colour.",
    "amber": "Warm orange-yellow used for figures or highlights.",
    "coral": "Pink-orange accent colour.",
    "magenta": "Saturated pink-purple accent colour.",
    "violet": "Blue-purple accent or gradient colour.",
    "green": "Green as a screen's accent or success colour.",
    "monochrome": "One hue plus neutrals, with no second colour in play.",
    # --- Component and pattern nouns the corpus keeps needing ---------------
    "badge": "A small circular or square marker attached to another element.",
    "thumbnail": "A small representative image inside a row or card.",
    "chip": "A compact pill-shaped control or label.",
    "scrim": "A translucent dark layer placed over content behind a sheet.",
    "call-to-action": "The single emphasised button or link a screen is built around.",
    "confirmation": "A short explicit step confirming an action before it commits.",
    "consent": "An explicit permission request made to the user.",
    "alert": "A prominent notice about a change, limit or problem.",
    "nav-bar": "The persistent bottom or top navigation bar of an app.",
    "floating-action-button": "A circular button floating above the content.",
    "data-table": "A many-row table of aligned values rather than a chart.",
    "week-strip": "A horizontal row of day cells marking a week.",
    "body-map": "A human-body diagram used to pick or show a location.",
    "sparkline": "A small inline trend line unaccompanied by axes.",
    "percentage": "A percentage figure used as the headline value.",
    "result": "The computed output of a tool or calculator.",
    "summary": "A condensed restatement of a longer set of details.",
    # --- Domain terms -------------------------------------------------------
    "photographic": "Built on real photography rather than illustration or flat colour.",
    "e-commerce": "Shopping, retail or a storefront.",
    "real-estate": "Property, housing or a listings marketplace.",
    "property": "An individual real-estate listing.",
    "listings": "A set of items offered by a seller or agent.",
    "logistics": "Moving goods: dispatch, routes and delivery windows.",
    "ordering": "Placing an order for goods, usually food.",
    "team": "A group of people working together inside a product.",
    "roster": "A named list of members with their state.",
    "medical": "Clinical or healthcare subject matter.",
    "dosage": "A measured amount of a medicine or treatment.",
    "privacy": "Data-sharing and location-sharing controls.",
    "spending": "Money going out, tracked by category.",
    "limit": "A cap on spending or usage.",
    "audit": "A full record intended for checking rather than browsing.",
    "itinerary": "A dated travel plan across several stops.",
    "pet": "Animal companions and their supplies.",
    "mood": "An emotional state selected by the user.",
    "caption": "A short explanatory line attached to an image.",
    "hand": "A hand holding the device, presented as a product shot.",
    "unit": "A unit of measurement the user can switch.",
    "album": "A released collection of songs as cover art plus title.",
    "centred": "Content deliberately centred on an otherwise empty ground.",
    "clause": "A contractual or policy condition shown for review.",
    "list-row": "One item in a vertical list, as distinct from a card grid.",
    "pink": "Pink as a screen's accent or signature colour.",
    "blue": "Blue as a screen's accent or primary-action colour.",
    "violet": "Blue-purple accent or gradient colour.",
    "arrow": "A drawn arrow used to direct the eye.",
    "checkbox": "A tick-box control for completing an item.",
    "histogram": "A bar distribution paired with range selection.",
    "day-view": "A calendar showing one day as a column of time slots.",
    "month-view": "A calendar showing a whole month as a date grid.",
    "install": "A first-run or add-to-device prompt.",
    "goal": "A savings or fitness target with progress toward it.",
    "savings": "Putting money aside toward a target.",
    "task": "A single to-do item.",
    "reminder": "A scheduled nudge for a future time.",
    "sharing": "Giving other people access to a list or item.",
    "catalogue": "A browsable wall of many separate items.",
    "memories": "Personal photos gathered and resurfaced.",
    "theme": "A light/dark appearance setting.",
    "laptop": "A laptop shown as context in a product shot.",
    "desk": "A desk surface shown as context in a product shot.",
    "mark": "A small character or logo mark used as a brand device.",
    "member": "One named person inside a shared group.",
    "token": "A named crypto asset with its own badge and ticker.",
    "circle": "A circular motif carried across a design as its signature shape.",
    "discount": "A reduction applied to a price, shown as its own line.",
    "totals": "A final summed block of labelled figures.",
    "time-slot": "A bookable delivery or appointment window.",
    "feature-tour": "A short sequence of explainer slides.",
    "play": "A play control or play affordance on media.",
    "statistics": "A row of headline counts describing a person or account.",
    "calculator": "A tool that takes named inputs and returns a computed figure.",
    "redesign": "A before/after pair showing the same screen built two ways.",
    "alignment": "Content deliberately aligned to one column and gutter.",
    "structure": "Containment and rhythm imposed on content, as opposed to a loose layout.",
    "hierarchy": "A clear order of importance across type and colour.",
    "ad": "An advertisement placed inside product content.",
    "reward": "Points, cash or credit earned for an action.",
    "referral": "Inviting someone in exchange for a benefit.",
    "book": "Book covers, reading or a personal library.",
    "scan": "Reading a code or object with the camera.",
    "figurative": "Illustration of a person or creature rather than an abstract shape.",
    "concept": "Exploratory work presented as a direction rather than a shipped screen.",
    "overlay": "Type or controls placed directly on an image.",
    "rating": "A score or star value attached to an item.",
    "depth": "Layering, shadow and tilt used to imply a third dimension.",
    "layered": "Several cards or panels stacked to imply z-order.",
    "tilt": "A frame deliberately rotated off-axis.",
    "mono-typography": "A monospaced face used as the display or accent type.",
    # --- Identity and mark construction -------------------------------------
    "wordmark": "A brand name set as type rather than drawn as a symbol.",
    "lockup": "A mark and a wordmark fixed together at one ratio.",
    "inverse": "A mark or layout reversed out of a dark ground.",
    "favicon": "An icon shown at the size a browser tab would render it.",
    "small-size": "An asset deliberately shown very small as a legibility test.",
    "large-size": "An asset deliberately shown very large as a construction test.",
    "variants": "The same asset presented across sizes, grounds or colourways.",
    "construction": "The geometry and guides a mark is built on.",
    "symmetry": "A composition mirrored about one or more axes.",
    "monogram": "A mark built from one or more initials.",
    "capsule": "A thick rounded bar used as a mark's primary shape.",
    "sphere": "A rendered ball or pebble applied as a character or brand object.",
    "orbit": "A ring or traced path circling a central body.",
    "star": "A star used as subject matter or as an accent.",
    "mountain": "Mountain or peak subject matter.",
    "owl": "An owl as a mascot or mark.",
    "smile": "A character's smile as the friendly element of a mark.",
    "still-life": "An arranged tabletop scene used as a brand photograph.",
    "cinematic": "Lit like a film frame, with strong directional light and depth.",
    "laboratory": "A lab or bench setting used as brand context.",
    "gold": "Gold or warm amber used as a premium accent.",
    "presentation": "An asset shown as a spec sheet or case-study board.",
    "character": "An illustrated person or creature used as the brand's face.",
    # --- Diagram, document and editorial vocabulary -------------------------
    "diagram": "A structured diagram rather than an interface.",
    "node": "A boxed element in a diagram with connectors attached.",
    "concept-map": "A radial map of related ideas around a central term.",
    "decision-tree": "A branching diagram of choices and their outcomes.",
    "architecture": "A system diagram showing parts and their connections.",
    "sequence": "An ordered set of stages read left to right.",
    "annotated": "A canvas carrying in-progress notes and labels.",
    "sketch": "Drawn by hand to look like a working draft.",
    "paper": "A paper-textured ground used behind a diagram.",
    "colour-ladder": "The same treatment shown at successive stages.",
    "swatch": "A colour or treatment sample presented as a tile.",
    "process": "A recipe-like sequence of steps.",
    "texture": "A grain, spray or weave applied as surface treatment.",
    "blur": "A softness applied to shapes or an image.",
    "tutorial": "An explainer showing how an effect was produced.",
    "legal": "Contract or policy text shown for reading or agreement.",
    "clause": "A contractual or policy condition shown for review.",
    "column": "A single narrow measure of body text.",
    "masthead": "A publication title treated as a display graphic.",
    "newsletter": "An email or update sign-up capture.",
    "billing": "Payment method, plan and invoice management.",
    "announcement": "A one-off launch or availability notice.",
    "benefit-list": "A numbered list of what a product gives you.",
    "mockup-grid": "A wall of small panels presenting many screens at once.",
    "landmark": "A recognisable building or monument used as subject matter.",
    "skyline": "A continuous run of buildings forming a horizon.",
    "skyline-row": "A horizontal line of landmarks presented as one scene.",
    "clouds": "Cloud formations used as the subject of an image.",
    "dawn": "Soft warm light at sunrise used as a palette.",
    "heart": "A heart used as a focal symbol.",
    "scribble": "Loose, visibly hand-drawn strokes left un-cleaned.",
    "spiral": "A spiral form used as a graphic or in a character.",
    "diagonal": "A strong diagonal division structuring the composition.",
    "rule": "A hairline rule used as a compositional device.",
    "orange": "Orange as an accent or dominant subject colour.",
    "cream": "Warm off-white used as a ground colour.",
    "soft-shadow": "A wide diffuse shadow lifting an element off the page.",
}

# new style -> definition (same shape as the existing entry)
NEW_STYLES = {
    "soft": "Rounded shapes, pastel or sanded colour, low-contrast edges. Friendly rather than severe.",
}


def main():
    apply = "--apply" in sys.argv
    with open(TAX, encoding="utf-8") as fh:
        tax = json.load(fh)

    tags = tax.setdefault("tags", {})
    styles = tax.setdefault("styles", {})

    existing = {k for k in tags if not k.startswith("_")}
    add_tags = {k: v for k, v in NEW_TAGS.items() if k not in existing}
    add_styles = {k: v for k, v in NEW_STYLES.items() if k not in styles}

    print(f"tags: {len(existing)} -> +{len(add_tags)}")
    for k, v in add_tags.items():
        print(f"   + {k:<18} {v}")
    print(f"styles: {len(styles)} -> +{len(add_styles)}")
    for k, v in add_styles.items():
        print(f"   + {k:<18} {v}")

    if not apply:
        print("\n(dry run - pass --apply to write)")
        return

    tags.update(add_tags)
    styles.update(add_styles)
    with open(TAX, "w", encoding="utf-8") as fh:
        json.dump(tax, fh, indent=1, ensure_ascii=False)
    print(f"\ntaxonomy now has {len([k for k in tags if not k.startswith('_')])} tags, "
          f"{len(styles)} styles")


if __name__ == "__main__":
    main()
